dat <- read.table("household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors = FALSE)
dat <- subset(dat, dat$Date %in% c("1/2/2007", "2/2/2007"))
dat$Date <- as.Date(dat$Date,format="%d/%m/%Y")
dat$DateTime <- strptime(paste(dat$Date,dat$Time), format = "%Y-%m-%d %H:%M:%S")
dat$Sub_metering_1 <- as.numeric(dat$Sub_metering_1) 
dat$Sub_metering_2 <- as.numeric(dat$Sub_metering_2) 
dat$Sub_metering_3 <- as.numeric(dat$Sub_metering_3) 

png(file="plot3.png")
plot(dat$DateTime, dat$Sub_metering_1, type="l", ylab="Energy sub metering",xlab="")
lines(dat$DateTime, dat$Sub_metering_2, type="l", col="red")
lines(dat$DateTime, dat$Sub_metering_3, type="l", col="blue")
legend("topright", c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), lty=c(1,1,1), col=c("black","red","blue"))
dev.off()
